import { PropsWithChildren } from 'react';
import { ApiResponse, InventoryInterface, InventoryPagesEnum, InventoryTypeEnum, ProductInterface, StoreInterface } from '../models';
import * as H from 'history';
export declare type InventoryContextData = {
    inventory: InventoryInterface | undefined;
    setDataInventory: (value: any) => void;
    product: ProductInterface | undefined;
    setDataProduct: (product: ProductInterface) => void;
    quantity: string;
    setQuantity: (value: string) => void;
    userStore: StoreInterface | undefined;
    setUserStore: (data: StoreInterface) => void;
    actionClearInventory: () => void;
    actionClearProduct: () => void;
    page: InventoryPagesEnum;
    setPage: (data: InventoryPagesEnum) => void;
    inventoryType: InventoryTypeEnum;
    setInventoryType: (data: InventoryTypeEnum) => void;
    getDataZonification: (data: string) => Promise<ApiResponse>;
    getInventoryID: () => Promise<ApiResponse>;
    getProduct: (key: string, type: string) => Promise<ApiResponse>;
    saveProduct: () => Promise<ApiResponse>;
    finishInventory: () => Promise<ApiResponse>;
    getTotalFurniture: () => Promise<ApiResponse>;
    history: H.History | undefined;
    setHistory: (data: H.History) => void;
    listSavedZonification: (filters: any) => Promise<any>;
    listFiltersZonification: () => Promise<any>;
    listProductsByZonification: (id: string) => Promise<any>;
    zoneSelected: any;
    setZoneSelected: (data: any) => void;
    userSelected: any;
    setUserSelected: (data: any) => void;
    furnituresSelected: any;
    setFurnituresSelected: (data: any) => void;
    sendListProductsBySavedZonification: (zonifications: any) => Promise<any>;
    inventoriesSelectedSaved: any;
    setInventoriesSelectedSaved: (data: any) => void;
    editProductCount: (amount: string) => Promise<ApiResponse>;
    setProductIdSelected: (id: string) => void;
    productIdSelected: string | undefined;
};
declare type InventoryProviderProps = {
    historyData: H.History;
    env: {
        country: string;
        inventoryApi: string;
        clientId: string;
    } | null;
    getStoreData: (() => Promise<StoreInterface>) | undefined;
};
export declare const InventoryContext: import("react").Context<InventoryContextData>;
export declare const InventoryProvider: ({ children, historyData, env, getStoreData, }: PropsWithChildren<InventoryProviderProps>) => JSX.Element;
export {};
