export declare enum InventoryPagesEnum {
    PAGE_LOAD_ZONE = "PAGE_LOAD_ZONE",
    PAGE_SCAN_ZONE = "PAGE_SCAN_ZONE",
    PAGE_SCAN_PRODUCT = "PAGE_SCAN_PRODUCT",
    PAGE_READ_PRODUCT = "PAGE_READ_PRODUCT",
    PAGE_SUCCESS = "PAGE_SUCCESS",
    PAGE_INVENTORY_SAVED_LIST = "PAGE_INVENTORY_SAVED_LIST",
    PAGE_INVENTORY_SAVED_FILTERS = "PAGE_INVENTORY_SAVED_FILTERS",
    PAGE_INVENTORY_SAVED_EDIT = "PAGE_INVENTORY_SAVED_EDIT",
    PAGE_INVENTORY_SAVED_LOAD_SUCCESS = "PAGE_INVENTORY_SAVED_LOAD_SUCCESS",
    PAGE_INVENTORY_SUMMARY_LOAD = "PAGE_INVENTORY_SUMMARY_LOAD"
}
