import Home from './AuthPages/Home/Home';
import Product from './AuthPages/Product/Product';
import Cart from './AuthPages/Cart/Cart';
import Shop from './AuthPages/Shop/Shop';
import NotFound from './NotFound/NotFound';
import ProductContainer from '../components/GridContainer/GridContainer';
import Category from './AuthPages/Category/Category';
import CategoryPage from './AuthPages/CategoryPage/CategoryPage';
import SignUp from './UnAuthorizedPages/RequestAccess/SignUp';
import PendingApprove from './UnAuthorizedPages/PendingAprove/PendingApprove';
import CreatePassword from './UnAuthorizedPages/CreatePassword/CreatePassword';
import ActiveAccount from './UnAuthorizedPages/ActiveAccount/ActiveAccount';
import PendingResetPassword from './UnAuthorizedPages/PendingResetPassword/PendingResetPassword';
import ForgotPassword from './UnAuthorizedPages/ForgotPassword/ForgotPassword';
import ResetPassword from './UnAuthorizedPages/ResetPassword/ResetPassword';
export { Home, Product, Cart, Shop, NotFound, ProductContainer, Category, CategoryPage, SignUp, PendingApprove, CreatePassword, ActiveAccount, PendingResetPassword, ForgotPassword, ResetPassword };
