import { PlanogramsPagesEnum } from "../models";
export declare const usePlanogram: () => {
    country: string;
    page: PlanogramsPagesEnum;
    loading: boolean;
    store: import("../models").StoreInterface;
    clearData: () => void;
    clearFormEvidence: () => void;
    departament: import("../models").OptionInterface;
    setDepartament: (value: import("../models").OptionInterface) => void;
    section: import("../models").OptionInterface;
    setSection: (value: import("../models").OptionInterface) => void;
    category: import("../models").OptionInterface;
    setCategory: (value: import("../models").OptionInterface) => void;
    showEvidenceModal: boolean;
    setShowEvidenceModal: (show: boolean) => void;
    routeToHome: () => void;
    routeToDepartamentList: () => void;
    routeToSectionList: () => void;
    routeToCategoryList: () => void;
    routeToDetail: () => void;
    getDepartaments: () => Promise<any>;
    getSections: () => Promise<any>;
    getCategories: () => Promise<any>;
    getDetail: () => Promise<any>;
    getPDFUrl: (value: string) => Promise<string>;
    formEvidence: any;
    setFormEvidence: any;
    isPlanogramImplemented: "" | "yes" | "no";
    setIsPlanogramImplemented: (value: "" | "yes" | "no") => void;
    showCamera: boolean;
    setShowCamera: (value: boolean) => void;
};
