export declare enum PlanogramsPagesEnum {
    PAGE_DEPARTAMENT_LIST = "PAGE_DEPARTAMENT_LIST",
    PAGE_SECTION_LIST = "PAGE_SECTION_LIST",
    PAGE_CATEGORY_LIST = "PAGE_CATEGORY_LIST",
    PAGE_DETAIL = "PAGE_DETAIL"
}
