import Header from './Header/Header';
import Container from './Container/Container';
import Slider from './Slider/Slider';
import HomeLayout from './NewProducts/NewProduct';
import ProductSlider from './ProductSlider/ProductSlider';
import RelatedProduct from './RelatedProduct/RelatedProduct';
import Footer from './Footer/Footer';
import PortalLayout from './PortalLayout';
import LinksCardsHome from './LinksCardsHome';
export { Header, Container, Slider, HomeLayout, ProductSlider, RelatedProduct, Footer, PortalLayout, LinksCardsHome };
