export declare enum ChecklistFlowPagesEnum {
    PAGE_CHECKLIST_TOOLS = "PAGE_CHECKLIST_TOOLS",
    PAGE_ITEMS_LIST_TOOLS = "PAGE_ITEMS_LIST_TOOLS",
    PAGE_CHECK_FEEDBACK_TOOLS = "PAGE_CHECK_FEEDBACK_TOOLS",
    PAGE_ITEMS_LIST_TASK = "PAGE_ITEMS_LIST_TASK",
    PAGE_CHECK_FEEDBACK_TASK = "PAGE_CHECK_FEEDBACK_TASK",
    PAGE_CHECKLIST_SUMMARY = "PAGE_CHECKLIST_SUMMARY"
}
