import { z } from 'zod';
export declare const productInformationResponseSchema: z.ZodObject<{
    tally: z.ZodString;
    price: z.ZodNumber;
    ntrStock: z.ZodNumber;
    averageSale: z.ZodNumber;
    image: z.ZodString;
    name: z.ZodString;
    ean: z.ZodString;
    sku: z.ZodString;
    provider: z.ZodString;
    brand: z.ZodString;
    netWeight: z.ZodNumber;
    expirationDate: z.ZodDate;
    usefulLifeLimit: z.ZodDate;
    noticeLevel: z.ZodEnum<["error", "warning", "info", "success", "neutral"]>;
}, "strip", z.ZodTypeAny, {
    tally: string;
    price: number;
    ntrStock: number;
    averageSale: number;
    image: string;
    name: string;
    ean: string;
    sku: string;
    provider: string;
    brand: string;
    netWeight: number;
    expirationDate: Date;
    usefulLifeLimit: Date;
    noticeLevel: "error" | "warning" | "info" | "success" | "neutral";
}, {
    tally: string;
    price: number;
    ntrStock: number;
    averageSale: number;
    image: string;
    name: string;
    ean: string;
    sku: string;
    provider: string;
    brand: string;
    netWeight: number;
    expirationDate: Date;
    usefulLifeLimit: Date;
    noticeLevel: "error" | "warning" | "info" | "success" | "neutral";
}>;
