export interface IProductSap {
    CostoInterno: number;
    Supplier: string;
    Sku: string;
    Nocatalog: boolean;
    CostoCpp: number;
    Description: string;
    BaseUnit: string;
    Category: string;
    SellUnit: string;
    CurrentPrice: number;
    Currency: string;
    Ean: string;
    SellOrg: string;
    SellCanal: string;
    Brand: string;
    BrandDesc: string;
    CostoMedio: number;
    StoreId: string;
    PriceType: string;
    PriceTypeDesc: string;
    Section: string;
    Rubro: string;
    Subrubro: string;
    ArtGroup: string;
    SkuType: string;
    stockDate: string;
    stockNRT: string;
}
